#model_list:
#  - model_name: gpt-5
#   litellm_params:
#     model: openai/gpt-5
#     api_key: os.environ/OPENAI_API_KEY
# - model_name: gpt-4o
#   litellm_params:
#     model: openai/gpt-4o
#     api_key: os.environ/OPENAI_API_KEY

#server:
#  host: 0.0.0.0
#  port: 4000

#model_list:
#  - model_name: grok-code-fast-1
#    litellm_params:
#      model: openrouter/x-ai/grok-code-fast-1
#      api_key: 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
#      api_base: https://openrouter.ai/api/v1

#  - model_name: deepseek-v3.1-terminus:exacto#
#    litellm_params:
#      model: openrouter/deepseek/deepseek-v3.1-terminus:exacto
#      api_key: sk-or-v1-79cf26bd617f4fedf94007b5476a21ce7e34b50ba6b72d4>
#      api_base: https://openrouter.ai/api/v1

#  - model_name: claude-opus-4.1
#    litellm_params:
#      model: openrouter/anthropic/claude-opus-4.1
#      api_key: sk-or-v1-79cf26bd617f4fedf94007b5476a21ce7e34b50ba6b72d4>
#      api_base: https://openrouter.ai/api/v1

#  - model_name: claude-sonnet-4.5
#    litellm_params:
#      model: openrouter/anthropic/claude-sonnet-4.5
#      api_key: sk-or-v1-79cf26bd617f4fedf94007b5476a21ce7e34b50ba6b72d4>
#      api_base: https://openrouter.ai/api/v1

#  - model_name: claude-haiku-4.5
#    litellm_params:
#      model: openrouter/anthropic/claude-haiku-4.5
#      api_key: sk-or-v1-79cf26bd617f4fedf94007b5476a21ce7e34b50ba6b72d4>
#      api_base: https://openrouter.ai/api/v1

#  - model_name: minimax-m2
#    litellm_params:
#      model: openrouter/minimax/minimax-m2
#      api_key: sk-or-v1-79cf26bd617f4fedf94007b5476a21ce7e34b50ba6b72d4>
#      api_base: https://openrouter.ai/api/v1
